### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by Chendaobin** [qq631192328/PFAudio#1]
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    cd /Users/chendaobin/Desktop/PFAudio
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name PFAudio -Onone -enforce-exclusivity=checked -DDEBUG -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -target x86_64-apple-ios10.0 -g -module-cache-path /Users/chendaobin/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Index/DataStore -Xfrontend -report-errors-to-debugger -swift-version 3 -I /Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Products/Debug-iphonesimulator -F /Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Products/Debug-iphonesimulator -c -j8 /Users/chendaobin/Desktop/PFAudio/PFAudio/ViewController.swift /Users/chendaobin/Desktop/PFAudio/PFAudio/AppDelegate.swift -output-file-map /Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PFAudio.build/Debug-iphonesimulator/PFAudio.build/Objects-normal/x86_64/PFAudio-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PFAudio.build/Debug-iphonesimulator/PFAudio.build/Objects-normal/x86_64/PFAudio.swiftmodule -Xcc -I/Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PFAudio.build/Debug-iphonesimulator/PFAudio.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PFAudio.build/Debug-iphonesimulator/PFAudio.build/PFAudio-generated-files.hmap -Xcc -I/Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PFAudio.build/Debug-iphonesimulator/PFAudio.build/PFAudio-own-target-headers.hmap -Xcc -I/Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PFAudio.build/Debug-iphonesimulator/PFAudio.build/PFAudio-all-target-headers.hmap -Xcc -iquote -Xcc /Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PFAudio.build/Debug-iphonesimulator/PFAudio.build/PFAudio-project-headers.hmap -Xcc -I/Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PFAudio.build/Debug-iphonesimulator/PFAudio.build/DerivedSources/x86_64 -Xcc -I/Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PFAudio.build/Debug-iphonesimulator/PFAudio.build/DerivedSources -Xcc -DDEBUG=1 -emit-objc-header -emit-objc-header-path /Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PFAudio.build/Debug-iphonesimulator/PFAudio.build/Objects-normal/x86_64/PFAudio-Swift.h -import-objc-header /Users/hpf/Desktop/Cocos\ Library/PFAudio/PFAudio/PFAudio/PFAudio-bridge-header.h -pch-output-dir /Users/chendaobin/Library/Developer/Xcode/DerivedData/PFAudio-hdwjhhdsizfacybdocvsrvenrlcq/Build/Intermediates.noindex/PrecompiledHeaders -Xcc -working-directory/Users/chendaobin/Desktop/PFAudio

<unknown>:0: error: generate-pch command failed with exit code 1 (use -v to see invocation)
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by qq631192328** [comment]
这个是桥接文件路径问题，现在设置成设置相对路径，已解决
